name: Testing for Telnyx with WebdriverIO in Docker
on:
  push:
    branches: fix
  pull_request:
    branches: fix
jobs:
  
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
   
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build  -f Dockerfile -t wdiochrome:v1 .
    - uses: addnab/docker-run-action@v3
      with:
        image: wdiochrome:v1
        run: |
          npm ci
          npm run wdio:docker      
    




